### PR TITLE
Change Typeface create, decrease apk size

### PR DESCRIPTION
**Pull request by madtcsa**
1. Important project to Android Studio 3.0.
2. Add Roboto Font Name Strings, change Typeface create by Typeface.create(String,int),delete Font files, decrease the Apk size from 3.6M(At Mac OS) to 3M.

### CODE REVIEW

**Comment by gsantner** [comment]
Hey there,

there is currently a big PR with a lot of changes to be merged. Maybe some parts are already done there. Please rebase and update the PR when the other one was merged

**Comment by madtcsa** [comment]
Ok

**Comment by MFlisar** [comment]
Can you really be sure that following will work on all phones:

    typeface = Typeface.create(getContext().getResources().getString(R.string.roboto_regular), Typeface.NORMAL);

From my understanding this means, that the roboto font must be installed on the system and I'm not sure if this precondition is always true. Your comment `<!-- roboto regular (from android 4.1) -->` lets me assume this is true for all android devices running android >= 4.1, is that true?

**Comment by conrad-heimbold** [comment]
@MFlisar @madtcsa : At least **Roboto-Condensed** is not available on all devices, see [this issue](https://github.com/scoute-dich/Blue-Minimal/issues/29)

**Comment by dkanada** [comment]
Not sure where the font is used in the app but we could always just remove it and use the system font if apk size is that important. I don't mind the extra MB used by the ttf file but I also don't really know if the extra font is entirey necessary in the first place.

**Comment by gsantner** [comment]
I too wouldn't save space on the wrong end. Especially noting about `<!-- roboto medium (from android 5.0) -->`: We support down to SDK 16 (at least for now), so this will surely break the app there.

**Comment by madtcsa** [comment]
yes, not all fonts installed on all devices, but  if the font is not available on all devices, the app can be installed and run well.

**Pull request closed without merging**
