### PR TITLE
Updated sc (Sardinian) translation

### PR DESCRIPTION
**Pull request by asereze**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for the updates!

**Comment by gsantner** [comment]
@dkanada 
Sorry for the recent quite, having much todo at work and not much time for foss.
Seen you did lots of rework recently. Is a new release taggable? Have seen the last release is 3 months out :smile: .

**Comment by dkanada** [comment]
There are a few outstanding issues before that. The main one is that some apps are currently not showing up in the launcher due to my work on profile support. Some apps also have more than one launchable activity, which the app doesn't detect properly.

**Comment by gsantner** [comment]
@dkanada 

Updated app to newer SDK, updated opoc tools (lots of cool new stuff), and fixed some bugs so the app doesnt crash on Android P.

**Comment by gsantner** [comment]
@dkanada 
Fixed icon size not being uniform, looks way better now

https://github.com/OpenLauncherTeam/openlauncher/commit/98f02465dab945ee715a43f82bc2bb0d72b0731d

before
screenshot-2019-04-28__14-01-16


after 
screenshot-2019-04-28__14-00-35

**Comment by gsantner** [comment]
@dkanada 
I think the issue with missing app drawer apps/icons is now fixed.

Can you please check the app and tell me if we are finally ready for a new release?

**Comment by dkanada** [comment]
@gsantner it looks good on my phone now, thanks for fixing that. I think we can add a new release on F-Droid now.

**Comment by gsantner** [comment]
@dkanada 
Hidden apps feature is currently not working (guess due the filteredApps comment).
Never used that myself,  but do you think its a blocker? Think not

**Pull request merged**
