### PR TITLE
Fix dependency 'SimpleFingerGestures'

### PR DESCRIPTION
**Pull request by r3r57**
Dependency has moved to github.com.

### CODE REVIEW

**Comment by dkanada** [comment]
@r3r57 not sure when we last updated this app on F-Droid but can you comment on the current master branch? I've been having issues uninstalling apps, which is why there isn't a release at the moment.

**Comment by r3r57** [comment]
@dkanada I don't experience any issues with uninstalling apps. What's the exact problem, maybe I can replicate it. Last update on F-Droid was 3/12/19.

**Comment by dkanada** [comment]
What version of Android are you on? I think it's related to Android 9 and the work profiles.

**Comment by r3r57** [comment]
I have Android 9, too.

**Comment by dkanada** [comment]
When you uninstall an app, does it immediately leave the app drawer? I'm actually on LineageOS 16 which might not be Android 9 behind the scenes.

**Comment by r3r57** [comment]
Hm...uninstalling apps works as expected for me.

**Pull request merged**
