### PR TITLE
fix typos: form-from and csutom-custom

### PR DESCRIPTION
**Pull request by conrad-heimbold**

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Shouldn't these be string resources?

**Comment by gsantner** [comment]
+1 from maintainer side to @EmmanuelMess comment

**Comment by BennyKok** [comment]
so the str res thing has been fixed in another pr, alright.

**Comment by gWOLF3** [comment]
Heads up guys, I just downloaded from Google Play store and still am seeing the same typo.

**Comment by gsantner** [comment]
only one person has access, and not really active ok project anymore. thus nobody will ever correct it on gplay. use fdroid.

**Comment by BennyKok** [comment]
Yes, as stated in the gplay description, the google play version will not be update-to-date, I have been inactive on this project for some time, life changes man.

**Pull request closed without merging**
