### PR TITLE
Notify

### PR DESCRIPTION
**Pull request by hobleyd**
I stuffed up and put two changes on master before I branched. Sorry.

This PR does 2 things as a result:
- Allows you to uninstall apps from the Desktop view.
- Provides initial support for notification badges (only working in Desktop view currently). It does not put a number in the badge, but just a small icon.

Any comments, please let me know.

Cheers,
David

### CODE REVIEW

**Comment by dkanada** [comment]
Are you familiar with the work profile feature on Android? We were planning on releasing another update a while ago, but I made some changes for that feature that kind of broke the app detection. I don't think we can release another version until that gets fixed.

**Comment by hobleyd** [comment]
I haven't had any specific experience with it. 

Certainly, I am running the latest version from github on my device as my primary launcher and seeing no problems. 

What, exactly, is broken? I am happy to take a look if you point me in the right direction. 

Cheers, 
David

**Comment by dkanada** [comment]
> only working in desktop view currently

Do you mean only on the desktop, not the app drawer? Also, notifications would definitely have to be an option in the settings, so please add an option there if you have time.

It looks like this PR included the commits from your other PR here, could you rebase this one to remove those?

**Comment by dkanada** [comment]
[This](https://github.com/OpenLauncherTeam/openlauncher/blob/752d2f097885e51d3cfeb504482c83b3f4a8edd5/app/src/main/java/com/benny/openlauncher/util/AppManager.java#L169) is the section I was working on for work profile support. If you're interested in fixing the issues feel free, it looks like I disabled it for now so it shouldn't block a release.

Since you added a notification badge we could extend that element and color it blue for apps from the work profile. I haven't looked at the code here in a while so I'm not sure how easy it would be.

**Comment by hobleyd** [comment]
Yes - for some reason, the notifications aren't showing up in the app drawer; but I'll work that out in the next couple of days hopefully. I'll add in a setting for it and resubmit the PR(s) tomorrow.

I'll also take a look at the work profile support. What are you wanting to achieve with this at a high level?

**Comment by dkanada** [comment]
Your other PR was fine so I just merged it :) I also tried to fix the commit stuff in this one but it ended up adding me to the logs, not sure why. If you fix master to match this repo and then reopen this PR with the three commits it should work again.

> What are you wanting to achieve with this at a high level?

Apparently lots of people use the work profile for installing certain apps they don't want to have access to the entire filesystem, which is a decent idea. Android will install the apps but block any filesystem access outside the profile. Normally these would show up in the launcher with some indication that they're in a work profile, but OpenLauncher doesn't show them at all.

**Comment by dkanada** [comment]
> for some reason, the notifications aren't showing up in the app drawer

I remember this! The app drawer uses a different view for apps than the desktop. If you wanted to remove one or the other that would be great, it's super annoying to have two different views.

**Comment by hobleyd** [comment]
OK, I have Notifications working mostly. The only issue I am aware of is that they don't update if you click on the Home button from another app; not sure why.

The AppDrawerGrid isn't working yet either as I feel like this is a bigger change and so I'll raise a separate PR for that once I have the work complete (to merge into a single approach).

Hopefully I have fixed my branch so it will apply cleanly. Let me know if you have any issues.

**Comment by dkanada** [comment]
I will merge this tomorrow, thanks for all the work! I'll be making some changes to fix a few outstanding bugs after that.

**Comment by dkanada** [comment]
Just noticed the minimum version bump to 23, that's probably a bit higher than I want it to be for another release. Before I push an update to F-Droid I'll have to look into adding some code to allow the minimum version to stay the same as before.

**Pull request merged**
