### PR TITLE
[WIP] Add translation in simplified Chinese

### PR DESCRIPTION
**Pull request by Therhokar**
My lapse~ This time is for buttons in the desktop.

### CODE REVIEW

**Comment by gsantner** [comment]
There is no need to hurry, just send us the localization when you are done. I'm marking this as WIP now

**Comment by BennyKok** [comment]
oh... ha ha

**Comment by Therhokar** [comment]
Well. Actually I've done all but four strings I don't understand clearly: "Interfaces" & "Feels" in "Preference Keys", and " Pinch" & "Unpinch" for gestures; all in /app, not /core. Can you explain them to me?

**Comment by BennyKok** [comment]
you can ignore the Preference Keys @Therhokar

**Comment by BennyKok** [comment]
As for pinch, it is a gesture for zooming with two fingers on the screen and unpinch is reverse of zooming action.

**Comment by Therhokar** [comment]
Done. I couldn't find a way to edit another file in this PR, so I created a new one. Please check it.

**Pull request closed without merging**
