### PR TITLE
Move untranslatable to own files, fixes #252

### LINKED ISSUE #252: Move untranslateable stuff to own file

### PR DESCRIPTION
**Pull request by gsantner**

### CODE REVIEW

**Comment by gsantner** [comment]
@BennyKok  @dkanada 

Hey OL team,

didn't hear from you since long time, in both conversation and development of openlauncher. Coming this time with an really important question.

I'm not feeling like development of OpenLauncher goes on, I did full rework some months ago, did a lot of bug fixing, introduced some new features - but still feeling like I'm gonna work here forever alone, without you both and without community. I can't stem this completely alone, neither bugfixing only and even more keeping up with latest android features or common launcher features.
 So the big question is, do we officially announce development halted on OpenLauncher and show that it is in maintainence-only mode? This also means that it should be taken offline at least from Google Play to not take users in the feeling "there comes more" and "this will get fixed", because probably it wont.

Best regards guys, hoping to hear from you :smile:

**Comment by BennyKok** [comment]
Hey @gsantner I am so sorry leaving this behind for some times, because I have been driven away by a lot of person matters (mostly school) and other non-android specific projects.

I am not so certain about the future of OpenLauncher after I have spend some times on looking other popular launcher that extends the launcher3 source, there is a lot of disadvantage of when compare this to others, many features is not supported and we needed to redo most of them, I am not so sure.

I have aware that there are still some peoples using the playstore version, and it has been outdated since the (around) the last 5.8 release. I still let it goes live simply because I still want people to be able to get it easily.

My Status
And recently I switched back to using Android, but I got another opportunities in working with a Germany based phone company "Carbon" on making their custom launcher, then realized that it is so easy to simply extent the launcher3 source, they decide to use some other third party open source launcher as the base (Lawnchair). However I think what makes OpenLauncher special is that it was started from scratch, it is lightweight, not like every other launcher outthere uses launcher3.

Decision to make
So I guess there is few options left for us to decide.

1. We all wanted to keep working this as a hobby, and I keep on pushing regular update to playstore (Also I will remove the paid support version since I am not contributing actively) , And we will need a redesign in usability and make everything fun.
2. Maybe we switch to maintainence-only mode, and going to update the info in PlayStore so people know this is only for testing, and we made clear instruction in app that the launcher wont have guarantee update. 
3. Not wanted to work on this anymore, because I don't have much time for this and feel like this is not going to work anymore.

**Comment by BennyKok** [comment]
I might be just back to some coding, as after switching back Android ha ha.. so I guess my choice will be the second one.

**Comment by dkanada** [comment]
I have been working on a lot of other projects, and I also feel like this launcher is at a level that I can use it as a daily driver without encountering any crashes whatsoever, so I have unfortunately stopped most of my work on this project. That is definitely the main reason, since I still love this launcher and use it every day on my phone.

There have been a few additions to the code that I feel should not be within the scope of a launcher though, which was another reason I stopped tinkering with it. I like my apps and programs as slim as possible, which is why I still use OpenLauncher over Lawnchair. I have mainly just been busy working on other stuff, so I am not sure I will be returning here to work on more code in the future.

**Comment by dkanada** [comment]
@gsantner thank you for your work this year on the launcher though, I know I havn't been the easiest to contact.

**Comment by gsantner** [comment]
Thanks for response.

The work till date is useless because it's not ready for an update, but biggest done. For the rest I don't know exactly howto fix it and there help is needed. The problem is dragging app from drawer to desktop, shows bad icon position before drop. Don't know who implemented it back then, but its better fixed by someone who has done that before.

**Comment by BennyKok** [comment]
I think I did the drag and drop preview thing back then, hum, I will try to have a check this week

**Pull request merged**
