### PR TITLE
Add Rotate screen option for tablets

### PR DESCRIPTION
**Pull request by axet**
I add 'Rotate screen' option for tablets only, phones (sw600dp<) will have this option hidden. Uses system settings for rotate or portrait mode (same as Google Now Launcher)

#120

### CODE REVIEW

**Comment by samansalamat** [comment]
does it work properly? 
could we set column or row size>?

**Comment by axet** [comment]
Does it answer your question?

screenshot_1506676259 screenshot_1506676266

screenshot_1506676297 screenshot_1506676305

**Comment by samansalamat** [comment]
perfect effort, does it have settings for drawer page?

**Comment by axet** [comment]
Doesn't like Google Now does. This is very rare used settings - it should be off by default for Phones and on for Tables (current implementation). User interaction is optional and only can be switched once per new installation. I see no uses for shortcut for drawer.

**Comment by samansalamat** [comment]
same as portrait mode, its great to have number of rows and columns for arranging icons in app drawer page (for example 5*6).

**Comment by axet** [comment]
Not sure what are you talking about.

Rotate has nothing to do with rows and columns, they not suppose to change. Only for phones, we can add fullscreen mode on landscape mode. In future releases...

Now just tablet support, as it says in commit.

How it is done in Google Now:

**Comment by samansalamat** [comment]
let me review your codes, i mean this option which is existed in nova launcher 
screenshot_2017-09-29-18-46-42
screenshot_2017-09-29-18-46-49

**Comment by axet** [comment]
Not what I'm interested in. I think this breaking icons layout. As you can see Google Now has no such hacks It should do automatic icon resizing. Just set grid once, and Launcher should only resize icons and change icons spaces. Keep in mind this is only phones feature. Tablets do not need it and phones in common do not rotate launcher / lock screens. So, not worth. Bad feature. Not requested by users. Wasting code and time.

**Comment by samansalamat** [comment]
does it swap size of row and column?

**Comment by axet** [comment]
No! Only spaces between.

**Comment by hibrn8** [comment]
Being able to change row and column sizes helps with oversized icons for one, and secondly helps with wasted space (due to large icon sizes). Users who can change columns and rows can make icons smaller in landscape and effectively increase their desktop space for widgets etc

**Pull request merged**
