### PR TITLE
openlauncher app attach the camera( issue #497) 

### PR DESCRIPTION
**Pull request by saechimdaeki**
I tried the camera function in this application. Cameras use basic cameras and can use front and rear cameras. Also, taking pictures is stored in the internal storage. #497

### CODE REVIEW

**Comment by dkanada** [comment]
Oh, you were thinking of implementing a custom activity to handle this. I figured a simple intent to open the system camera would be better so we can utilize a camera app with more features.

**Comment by saechimdaeki** [comment]
(MediaStore.ACTION_IMAGE_CAPTURE);Do you mean use this ?

**Comment by dkanada** [comment]
Yeah, that's what I was thinking about.

**Comment by saechimdaeki** [comment]
I made call the system camera installed on cell phone.

**Comment by saechimdaeki** [comment]
(MediaStore.ACTION_IMAGE_CAPTURE) gained the characteristics of the application by accessing and opening the camera installed through (MediaStore.INTENT_ACTION_STILL_IMAGE_CAMERA) because only the basic camera is available and the pictures taken through this function are not available in the gallery.

**Comment by dkanada** [comment]
Hmmm, that's not what we want. There has to be a way to just open the system camera and let it handle everything. I'll look into it and if I can't find anything we can use your custom activity.

**Comment by saechimdaeki** [comment]
The new committed method does not use custom activity. Call the system camera to do everything you say. Do you want me to delete the custom activity class?

**Comment by saechimdaeki** [comment]
This is the running screen.

this1

Press button to control all systems.

this2

**Comment by saechimdaeki** [comment]
As you can see on the running screen, you can access all installed cameras. Do not use custom activity.

**Comment by gsantner** [comment]
@saechimdaeki 
For requesting a camera picture from an other app, no additional permissions are needed. As discussued, please leave away all kinds of custom camera implementaion logic & UI. Let the user use his own familar camera app.

For this, theres code already in OpenLauncher in the ShareUtil class. It's very low amount of stuff that needs to be added to work with this app as it does cover nearly everything. 

That class is also used at my [MemeTastic](https://github.com/gsantner/memetastic) app, you can see there how it works.

I'm now declining this PR and suggest to start with a fresh branch.

**Comment by saechimdaeki** [comment]
@gsantner Then I'll delete the custom activity and open a new branch.

**Comment by gsantner** [comment]
thanks!

**Comment by saechimdaeki** [comment]
@gsantner (MediaStore.INTENT_ACTION_STILL_IMAGE_CAMERA) It seems to be solved by using this alone.

**Comment by gsantner** [comment]
What is resolved? I'm sorry not have followed the discussion much.

I'm seeing still lots of activity & own camera

grafik

**Comment by saechimdaeki** [comment]
@Generator The first attempt was to create a custom camera of openauncher's own. I've created a custom activity, but I have to do an approach without using it, so I'll delete the related ones and open a new branch. They used to be customactivity. I'll delete them. and open new branch

**Comment by gsantner** [comment]
OK I ll leave that up to you in which branch an PR, close and open as you wish

**Comment by saechimdaeki** [comment]
@gsantner  https://github.com/OpenLauncherTeam/openlauncher/pull/521 is new pr .
Only camera short cut function is implemented.

**Pull request closed without merging**
