### PR TITLE
Updated de (German) translation

### PR DESCRIPTION
**Pull request by tacticalDevC**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by BennyKok** [comment]
Oh still have the conflicts, why that..?

**Comment by gsantner** [comment]
tactical, can you delete your github repo and your local stringlate copy of the repo? something seems to be very outdated

**Comment by tacticalDevC** [comment]
@gsantner deleting and making a new PR?

**Comment by gsantner** [comment]
as you see you keep getting same old sources, reopening PR doesnt make it different

**Comment by tacticalDevC** [comment]
@gsantner So... Syncing up and new PR

**Pull request merged**
