### PR TITLE
reorganize and clean Fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
see #655 – this reorg should enable F-Droid to use the project's metadata, thus giving you full control over descriptions, screenshots etc. According to the [Fastlane structures](https://gitlab.com/snippets/1895688)…

* `metadata/` was renamed to `fastlane/metadata/android`
* images (`phoneScreenshots`, `featureGraphic.png`) have been moved to `fastlane/metadata/android/images` and the "stable" icon was placed there as `icon.png`
* remaining graphic files were moved to `assets/`
* `README.md` was adjusted accordingly concerning the new image locations

I hope I caught it all, please cross-check. You can always build on this, I hope my above linked "Cheat-Sheet" proves helpful.

Once this PR was merged and a new tag is available, please let us (at F-Droid) know so we can switch to the new metadata. I'll gladly make the corresponding MR at fdroiddata for you as well.

### CODE REVIEW

**Comment by gsantner** [comment]
What I don't quite get is what you mean with 

> Once this PR was merged and a new tag is available, please let us (at F-Droid) know so we can switch to the new metadata. I'll gladly make the corresponding MR at fdroiddata for you as well.

..fdroidserver usually picks up the metadta from the tagged commit and if it's there it works as is. Or is there something new that I don't know yet?

**Comment by IzzySoft** [comment]
> ..fdroidserver usually picks up the metadta from the tagged commit and if it's there it works as is. Or is there something new that I don't know yet?

Maybe: "order of precendence".

* first, Triple-T is fetched and put in place.
* second, Fastlane is fetched and put in place (overwriting whatever Triple-T brought)
* third, whatever local metadata exist overwrite what the above brought
* last, metadata inside the `.yml` files is put on top.

Currently, for OpenLauncher there are local `summary.txt` overwriting your `short_description.txt` – and the description inside the `.yml` overwriting your `en-US/full_description.txt`. Those must be removed – but not before your Fastlane is tagged and picked.

That said: let me fetch those short descriptions and add them to your Fastlane, so the work of our translators was not in vain. That OK with you? Will bring you short descriptions for 16 additional languages if you'd take them.

**Comment by IzzySoft** [comment]
> let me fetch those short descriptions and add them to your Fastlane

Can be done with a separate PR as well if you prefer – so feel free going ahead and merging this one as-is :wink:

**Comment by gsantner** [comment]
thx merged

**Comment by IzzySoft** [comment]
Great! Thanks! Continuing in the issue then.

**Pull request merged**
